name: Build & Deploy Staging

on:
  push:
    branches: [main]
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Staging AarnaLaw
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username

          script: |
            cd /var/www/newwebsite
